
[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

# decorations = "Buttonless"

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 14

[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
